### ISSUE TITLE
Error : javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by 28kayak** [28kayak/Alicebot#1]
Sraixにアクセスしようとすると出てきてしまう。

```sh
You: show me a cat
STATE=show me a cat:THAT=unknown:TOPIC=unknown
normalized = show me a cat
Matched: SHOW ME A * <THAT> * <TOPIC> * reductions1.aiml
0. <srai>SHOW ME cat</srai> from SHOW ME A * <THAT> * <TOPIC> * topic=unknown) 
Matched: SHOW ME * <THAT> * <TOPIC> * picture.aiml
1. <srai>PICTUREBLAB cat</srai> from SHOW ME * <THAT> * <TOPIC> * topic=unknown) 
Matched: PICTUREBLAB * <THAT> * <TOPIC> * picture.aiml
--> localIPAddress = fe80:0:0:0:aede:48ff:fe00:1122
Sraix url='https://weannie.pannous.com/api?input=SHOW+ME+cat&locale=en_US&timeZone=540&login=test-user&ip=fe80:0:0:0:aede:48ff:fe00:1122&botid=0&key=guest&exclude=Dialogues,ChatBot&out=json'
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:457)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at org.alicebot.ab.utils.NetworkUtils.responseContent(NetworkUtils.java:50)
	at org.alicebot.ab.Sraix.sraixPannous(Sraix.java:111)
	at org.alicebot.ab.Sraix.sraix(Sraix.java:42)
	at org.alicebot.ab.AIMLProcessor.sraix(AIMLProcessor.java:385)
	at org.alicebot.ab.AIMLProcessor.recursEval(AIMLProcessor.java:1050)
	at org.alicebot.ab.AIMLProcessor.evalTagContent(AIMLProcessor.java:246)
	at org.alicebot.ab.AIMLProcessor.recursEval(AIMLProcessor.java:1040)
	at org.alicebot.ab.AIMLProcessor.evalTemplate(AIMLProcessor.java:1133)
	at org.alicebot.ab.AIMLProcessor.srai(AIMLProcessor.java:324)
	at org.alicebot.ab.AIMLProcessor.recursEval(AIMLProcessor.java:1046)
	at org.alicebot.ab.AIMLProcessor.evalTagContent(AIMLProcessor.java:246)
	at org.alicebot.ab.AIMLProcessor.recursEval(AIMLProcessor.java:1040)
	at org.alicebot.ab.AIMLProcessor.evalTemplate(AIMLProcessor.java:1133)
	at org.alicebot.ab.AIMLProcessor.respond(AIMLProcessor.java:187)
	at org.alicebot.ab.AIMLProcessor.respond(AIMLProcessor.java:162)
	at org.alicebot.ab.Chat.respond(Chat.java:115)
	at org.alicebot.ab.Chat.respond(Chat.java:140)
	at org.alicebot.ab.Chat.multisentenceRespond(Chat.java:165)
	at Chatbot.main(Chatbot.java:51)
Sraix 'SHOW+ME+cat' failed
Matched: SRAIXFAILED <THAT> * <TOPIC> * sraix.aiml
writeCertainIFCaegories learnf.aiml size= 11
Charlotte: This is what cat looks like.I don't know the answer.
Perhaps we should try a web search.
<oob><search>show me a cat</search></oob>
```

**Comment by 28kayak** [comment]
One of the solution we can do is to give up secure connection to `weannie.pannous.com`.  
That means, changing ` https:// ` to `http://` 
In `Sarix.java`  file around line-118, 
```sh
String url = "https://weannie.pannous.com/api?input=" + input 
                + "&locale=en_US&timeZone=" + offset + locationString 
                + "&login=" + MagicStrings.pannous_login 
                + "&ip=" + NetworkUtils.localIPAddress() 
                + "&botid=0&key=" + MagicStrings.pannous_api_key 
                + "&exclude=Dialogues,ChatBot&out=json";
```
To
```sh
  String url = "http://weannie.pannous.com/api?input=" + input 
                  + "&locale=en_US&timeZone=" + offset + locationString 
                  + "&login=" + MagicStrings.pannous_login 
                  + "&ip=" + NetworkUtils.localIPAddress() 
                  + "&botid=0&key="+ MagicStrings.pannous_api_key 
                  + "&exclude=Dialogues,ChatBot&out=json";
```

Or, change the keystore to accept unverified SSL certificate. (NOT RECOMMENDED)
